MATRIX_ROWS = 25
MATRIX_COLS = 50
CELL_SIZE = 20
SCREEN_WIDTH = MATRIX_COLS * CELL_SIZE
SCREEN_HEIGHT = MATRIX_ROWS * CELL_SIZE
SOLDIER_WIDTH = 2
SOLDIER_HEIGHT = 4
SOLDIER_SIZE = (SOLDIER_WIDTH, SOLDIER_HEIGHT)

FLAG_HEIGHT = 4
FLAG_WIDTH = 3
MINE_HEIGHT = 3
MINE_WIDTH = 2
BACKGROUND_COLOR = (37, 150, 190)

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3